// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AiCostSetting struct {
	UserID                    pgtype.UUID
	Agent                     string
	InputCostPerMillionCents  int32
	OutputCostPerMillionCents int32
	ModifiedAt                pgtype.Timestamptz
}

type ApiKey struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Name           string
	KeyHash        string
	KeyFingerprint string
	Scopes         []string
	LastUsedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type CustomRule struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Action      string
	Source      string
	Operation   string
	SourceValue string
	Priority    int32
	CreatedAt   pgtype.Timestamptz
	ModifiedAt  pgtype.Timestamptz
}

type CustomRuleDestination struct {
	ID               pgtype.UUID
	RuleID           pgtype.UUID
	Destination      string
	DestinationValue string
}

type CustomRulesProgress struct {
	UserID          pgtype.UUID
	Status          string
	PercentComplete int32
	Total           int32
	Changed         int32
	Deleted         int32
	Error           pgtype.Text
	StartedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	ModifiedAt      pgtype.Timestamptz
}

type DataDump struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Type            string
	Status          string
	PercentComplete float64
	DownloadUrl     pgtype.Text
	IsProcessing    bool
	IsStuck         bool
	HasFailed       bool
	ExpiresAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type EditorPlugin struct {
	Key     string
	Name    string
	Version pgtype.Text
}

type ExternalDuration struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	ExternalID string
	Provider   string
	Entity     string
	Type       string
	Category   pgtype.Text
	StartTime  float64
	EndTime    float64
	Project    pgtype.Text
	Branch     pgtype.Text
	Language   pgtype.Text
	Meta       pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type Goal struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Title            string
	CustomTitle      pgtype.Text
	Delta            string
	Seconds          int32
	Languages        []string
	Editors          []string
	Projects         []string
	IgnoreDays       []string
	IgnoreZeroDays   bool
	ImproveByPercent pgtype.Float8
	IsEnabled        bool
	IsInverse        bool
	IsSnoozed        bool
	SnoozeUntil      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	ModifiedAt       pgtype.Timestamptz
}

type GoalEvaluation struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	GoalID        pgtype.UUID
	PeriodStart   pgtype.Timestamptz
	PeriodEnd     pgtype.Timestamptz
	ActualSeconds int32
	TargetSeconds int32
	Percent       int32
	IsComplete    bool
	EvaluatedAt   pgtype.Timestamptz
}

type Heartbeat struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Entity             string
	Type               string
	Category           pgtype.Text
	Time               float64
	Project            pgtype.Text
	Branch             pgtype.Text
	Language           pgtype.Text
	MachineNameID      pgtype.UUID
	MachineName        pgtype.Text
	Editor             pgtype.Text
	OperatingSystem    pgtype.Text
	Dependencies       pgtype.Text
	Lines              pgtype.Int4
	LineNumber         pgtype.Int4
	CursorPos          pgtype.Int4
	IsWrite            bool
	AiLineChanges      pgtype.Int4
	HumanLineChanges   pgtype.Int4
	AiSession          pgtype.Text
	AiInputTokens      pgtype.Int4
	AiOutputTokens     pgtype.Int4
	AiPromptLength     pgtype.Int4
	AiSubscriptionPlan pgtype.Text
	CreatedAt          pgtype.Timestamptz
	CommitHash         pgtype.Text
	Plugin             pgtype.Text
	PluginVersion      pgtype.Text
	EditorVersion      pgtype.Text
	Architecture       pgtype.Text
}

type Leaderboard struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Name       string
	TimeRange  string
	CreatedAt  pgtype.Timestamptz
	ModifiedAt pgtype.Timestamptz
}

type LeaderboardMember struct {
	LeaderboardID pgtype.UUID
	UserID        pgtype.UUID
	Role          string
}

type MachineName struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Name       string
	Value      pgtype.Text
	Ip         *netip.Addr
	Timezone   pgtype.Text
	LastSeenAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type OauthApp struct {
	ID                      pgtype.UUID
	UserID                  pgtype.UUID
	Name                    string
	ClientID                string
	ClientSecretHash        string
	ClientSecretFingerprint string
	RedirectUris            []string
	Scopes                  []string
	CreatedAt               pgtype.Timestamptz
	ModifiedAt              pgtype.Timestamptz
}

type OauthAuthorizationCode struct {
	ID              pgtype.UUID
	AppID           pgtype.UUID
	UserID          pgtype.UUID
	CodeHash        string
	CodeFingerprint string
	RedirectUri     string
	Scopes          []string
	ExpiresAt       pgtype.Timestamptz
	UsedAt          pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type OauthToken struct {
	ID                      pgtype.UUID
	AppID                   pgtype.UUID
	UserID                  pgtype.UUID
	AccessTokenHash         string
	AccessTokenFingerprint  string
	RefreshTokenHash        pgtype.Text
	RefreshTokenFingerprint pgtype.Text
	Scopes                  []string
	ExpiresAt               pgtype.Timestamptz
	RevokedAt               pgtype.Timestamptz
	LastUsedAt              pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
}

type ProgramLanguage struct {
	Name  string
	Color string
}

type Project struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Name             string
	Color            pgtype.Text
	HasPublicUrl     bool
	Badge            pgtype.Text
	FirstHeartbeatAt pgtype.Timestamptz
	LastHeartbeatAt  pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type ShareToken struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Name             string
	TokenHash        string
	TokenFingerprint string
	LastUsedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type StatsCache struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Range             string
	Data              []byte
	IsUpToDate        bool
	PercentCalculated int32
	ComputedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type User struct {
	ID                         pgtype.UUID
	GithubID                   int64
	GithubUsername             string
	Email                      pgtype.Text
	FullName                   pgtype.Text
	AvatarUrl                  pgtype.Text
	Country                    pgtype.Text
	Timezone                   string
	TimeoutMinutes             int32
	WritesOnly                 bool
	IsHireable                 bool
	CreatedAt                  pgtype.Timestamptz
	ModifiedAt                 pgtype.Timestamptz
	HasPublicProfile           bool
	HeartbeatRetentionDays     int32
	PublicUsername             pgtype.Text
	PublicDisplayName          pgtype.Text
	PublicGithubLinkEnabled    bool
	PublicShowTotalTime        bool
	PublicShowProjects         bool
	PublicProjectVisibility    string
	PublicShowLanguages        bool
	PublicShowEditors          bool
	PublicShowMachines         bool
	PublicShowOperatingSystems bool
	PublicShowCategories       bool
	PublicShowAi               bool
	PublicShowSummaries        bool
}
