// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: phase1.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, github_id, github_username, email, full_name, avatar_url, timezone, timeout_minutes, writes_only, is_hireable, has_public_profile, country, heartbeat_retention_days,
  public_username, public_display_name, public_github_link_enabled, public_show_total_time, public_show_projects, public_project_visibility,
  public_show_languages, public_show_editors, public_show_machines, public_show_operating_systems, public_show_categories, public_show_ai,
  public_show_summaries
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID                         pgtype.UUID
	GithubID                   int64
	GithubUsername             string
	Email                      pgtype.Text
	FullName                   pgtype.Text
	AvatarUrl                  pgtype.Text
	Timezone                   string
	TimeoutMinutes             int32
	WritesOnly                 bool
	IsHireable                 bool
	HasPublicProfile           bool
	Country                    pgtype.Text
	HeartbeatRetentionDays     int32
	PublicUsername             pgtype.Text
	PublicDisplayName          pgtype.Text
	PublicGithubLinkEnabled    bool
	PublicShowTotalTime        bool
	PublicShowProjects         bool
	PublicProjectVisibility    string
	PublicShowLanguages        bool
	PublicShowEditors          bool
	PublicShowMachines         bool
	PublicShowOperatingSystems bool
	PublicShowCategories       bool
	PublicShowAi               bool
	PublicShowSummaries        bool
}

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.TimeoutMinutes,
		&i.WritesOnly,
		&i.IsHireable,
		&i.HasPublicProfile,
		&i.Country,
		&i.HeartbeatRetentionDays,
		&i.PublicUsername,
		&i.PublicDisplayName,
		&i.PublicGithubLinkEnabled,
		&i.PublicShowTotalTime,
		&i.PublicShowProjects,
		&i.PublicProjectVisibility,
		&i.PublicShowLanguages,
		&i.PublicShowEditors,
		&i.PublicShowMachines,
		&i.PublicShowOperatingSystems,
		&i.PublicShowCategories,
		&i.PublicShowAi,
		&i.PublicShowSummaries,
	)
	return i, err
}

const listHeartbeatsForRange = `-- name: ListHeartbeatsForRange :many
SELECT id, user_id, entity, type, category, time, project, branch, language, machine_name_id,
  machine_name, plugin, plugin_version, editor, editor_version, operating_system, architecture,
  dependencies, lines, line_number, cursor_pos, is_write, ai_line_changes, human_line_changes,
  ai_session, ai_input_tokens, ai_output_tokens, ai_prompt_length, ai_subscription_plan, created_at,
  commit_hash
FROM heartbeats
WHERE user_id = $1 AND time >= $2 AND time < $3
ORDER BY time ASC
`

type ListHeartbeatsForRangeParams struct {
	UserID pgtype.UUID
	Time   float64
	Time_2 float64
}

type ListHeartbeatsForRangeRow struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Entity             string
	Type               string
	Category           pgtype.Text
	Time               float64
	Project            pgtype.Text
	Branch             pgtype.Text
	Language           pgtype.Text
	MachineNameID      pgtype.UUID
	MachineName        pgtype.Text
	Plugin             pgtype.Text
	PluginVersion      pgtype.Text
	Editor             pgtype.Text
	EditorVersion      pgtype.Text
	OperatingSystem    pgtype.Text
	Architecture       pgtype.Text
	Dependencies       pgtype.Text
	Lines              pgtype.Int4
	LineNumber         pgtype.Int4
	CursorPos          pgtype.Int4
	IsWrite            bool
	AiLineChanges      pgtype.Int4
	HumanLineChanges   pgtype.Int4
	AiSession          pgtype.Text
	AiInputTokens      pgtype.Int4
	AiOutputTokens     pgtype.Int4
	AiPromptLength     pgtype.Int4
	AiSubscriptionPlan pgtype.Text
	CreatedAt          pgtype.Timestamptz
	CommitHash         pgtype.Text
}

func (q *Queries) ListHeartbeatsForRange(ctx context.Context, arg ListHeartbeatsForRangeParams) ([]ListHeartbeatsForRangeRow, error) {
	rows, err := q.db.Query(ctx, listHeartbeatsForRange, arg.UserID, arg.Time, arg.Time_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHeartbeatsForRangeRow
	for rows.Next() {
		var i ListHeartbeatsForRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Entity,
			&i.Type,
			&i.Category,
			&i.Time,
			&i.Project,
			&i.Branch,
			&i.Language,
			&i.MachineNameID,
			&i.MachineName,
			&i.Plugin,
			&i.PluginVersion,
			&i.Editor,
			&i.EditorVersion,
			&i.OperatingSystem,
			&i.Architecture,
			&i.Dependencies,
			&i.Lines,
			&i.LineNumber,
			&i.CursorPos,
			&i.IsWrite,
			&i.AiLineChanges,
			&i.HumanLineChanges,
			&i.AiSession,
			&i.AiInputTokens,
			&i.AiOutputTokens,
			&i.AiPromptLength,
			&i.AiSubscriptionPlan,
			&i.CreatedAt,
			&i.CommitHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
