import { readFileSync } from "node:fs";

const source = readFileSync("app/(console)/integrations/page.tsx", "utf8");

assertIncludes("integrations page exposes native Stint CLI recipe", source, "bin/stint config init");
assertIncludes("integrations page documents api-keys command", source, "bin/stint api-keys");
assertIncludes("integrations page documents api-keys create command", source, 'bin/stint api-keys create "Editor key" --scope write_heartbeats --scope read_stats');
assertIncludes("integrations page documents api-keys delete command", source, "bin/stint api-keys delete API_KEY_ID");
assertIncludes("integrations page documents oauth-apps command", source, "bin/stint oauth-apps");
assertIncludes("integrations page documents oauth-apps create command", source, 'bin/stint oauth-apps create "Local OAuth app" --redirect-uri http://localhost:3000/callback --scope read_stats');
assertIncludes("integrations page documents oauth-apps delete command", source, "bin/stint oauth-apps delete OAUTH_APP_ID");
assertIncludes("integrations page documents OAuth authorization-code exchange command", source, "bin/stint oauth token --client-id OAUTH_CLIENT_ID --client-secret OAUTH_CLIENT_SECRET --code AUTH_CODE --redirect-uri http://localhost:3000/callback");
assertIncludes("integrations page documents OAuth refresh command", source, "bin/stint oauth token --client-id OAUTH_CLIENT_ID --client-secret OAUTH_CLIENT_SECRET --refresh-token REFRESH_TOKEN");
assertIncludes("integrations page documents OAuth revoke command", source, "bin/stint oauth revoke ACCESS_OR_REFRESH_TOKEN --client-id OAUTH_CLIENT_ID --client-secret OAUTH_CLIENT_SECRET");
assertIncludes("integrations page documents account command", source, "bin/stint account");
assertIncludes("integrations page documents account update command", source, "bin/stint account update account.json");
assertIncludes("integrations page documents account delete command", source, "bin/stint account delete --confirm");
assertIncludes("integrations page documents meta command", source, "bin/stint meta");
assertIncludes("integrations page documents api docs command", source, "bin/stint api-docs");
assertIncludes("integrations page documents leaders command", source, "bin/stint leaders");
assertIncludes("integrations page documents filtered leaders command", source, "bin/stint leaders --language Go --country US");
assertIncludes("integrations page documents editors command", source, "bin/stint editors");
assertIncludes("integrations page documents program languages command", source, "bin/stint program-languages");
assertIncludes("integrations page documents public user command", source, "bin/stint users public-username");
assertIncludes("integrations page documents public user stats command", source, "bin/stint users public-username stats last_7_days");
assertIncludes("integrations page documents public user stats range flag", source, "bin/stint users public-username stats --range last_30_days");
assertIncludes("integrations page documents public user summaries command", source, "bin/stint users public-username summaries");
assertIncludes("integrations page documents public user summaries window", source, "bin/stint users public-username summaries --start 2026-06-01 --end 2026-06-30");
assertIncludes("integrations page documents public share stats command", source, "bin/stint share SHARE_TOKEN stats");
assertIncludes("integrations page documents public share stats range", source, "bin/stint share SHARE_TOKEN stats --range last_7_days");
assertIncludes("integrations page documents public share summaries command", source, "bin/stint share SHARE_TOKEN summaries");
assertIncludes("integrations page documents public share summaries window", source, "bin/stint share SHARE_TOKEN summaries --start 2026-06-01 --end 2026-06-30");
assertIncludes("integrations page documents health command", source, "bin/stint health");
assertIncludes("integrations page documents ingestion health command", source, "bin/stint health ingestion");
assertIncludes("integrations page documents dev seed command", source, "bin/stint dev seed-key --github-id 4001 --username local-dev");
assertIncludes("integrations page documents dev purge command", source, "bin/stint dev heartbeats-purge --retention-days 0");
assertIncludes("integrations page documents dev leaderboard command", source, "bin/stint dev leaderboard-update --range last_7_days");
assertIncludes("integrations page documents dev goals command", source, "bin/stint dev goals-evaluate");
assertIncludes("integrations page documents DEFAULT config support", source, "[DEFAULT]");
assertIncludes("integrations page documents WAKATIME_HOME resource path", source, "$WAKATIME_HOME/");
assertIncludes("integrations page documents api_url validation", source, "validates and normalizes");
assertIncludes("integrations page documents zero timeout support", source, "timeout = 0");
assertIncludes("integrations page documents invalid heartbeat rate limit default", source, "treats non-integer");
assertIncludes("integrations page documents negative heartbeat rate limit disables", source, "treats negative");
assertIncludes("integrations page documents case-insensitive scalar keys", source, "case-insensitive");
assertIncludes("integrations page documents quoted scalar values", source, "quoted scalar values");
assertIncludes("integrations page documents comma-separated include/exclude flags", source, "comma-separated include/exclude flags");
assertIncludes("integrations page documents comma-preserving regex lists", source, "newline-separated regex lists with commas preserved inside patterns");
assertIncludes("integrations page documents Perl-style regex fallback", source, "Perl-style lookahead regex fallback");
assertIncludes("integrations page documents api-key flag alias", source, "--api-key");
assertIncludes("integrations page documents heartbeats command", source, 'bin/stint heartbeats "$(date +%F)"');
assertIncludes("integrations page documents stats command", source, "bin/stint stats last_7_days");
assertIncludes("integrations page documents durations command", source, 'bin/stint durations "$(date +%F)" --slice-by language');
assertIncludes("integrations page documents summaries command", source, "bin/stint summaries 2026-06-01 2026-06-30");
assertIncludes("integrations page documents projects command", source, "bin/stint projects stint");
assertIncludes("integrations page documents project commits command", source, "bin/stint projects stint commits --branch main");
assertIncludes("integrations page documents project commit detail command", source, "bin/stint projects stint commits COMMIT_HASH");
assertIncludes("integrations page documents all-time command", source, "bin/stint all-time");
assertIncludes("integrations page documents machine-names command", source, "bin/stint machine-names");
assertIncludes("integrations page documents user-agents command", source, "bin/stint user-agents");
assertIncludes("integrations page documents goals command", source, "bin/stint goals");
assertIncludes("integrations page documents goals create command", source, "bin/stint goals create goal.json");
assertIncludes("integrations page documents goals update command", source, "bin/stint goals update GOAL_ID goal.json");
assertIncludes("integrations page documents goals delete command", source, "bin/stint goals delete GOAL_ID");
assertIncludes("integrations page documents insights command", source, "bin/stint insights languages last_7_days");
assertIncludes("integrations page documents external-durations command", source, "bin/stint external-durations");
assertIncludes("integrations page documents external-durations create command", source, "bin/stint external-durations create external-duration.json");
assertIncludes("integrations page documents external-durations bulk command", source, "bin/stint external-durations bulk external-durations.json");
assertIncludes("integrations page documents external-durations delete command", source, "bin/stint external-durations delete 00000000-0000-4000-8000-000000000000");
assertIncludes("integrations page documents external-durations bulk delete command", source, "bin/stint external-durations delete --ids id-1,id-2");
assertIncludes("integrations page documents custom-pricing command", source, "bin/stint custom-pricing");
assertIncludes("integrations page documents custom-pricing upsert command", source, "bin/stint custom-pricing upsert custom-pricing.json");
assertIncludes("integrations page documents custom-pricing delete command", source, "bin/stint custom-pricing delete gpt-5-codex");
assertIncludes("integrations page documents pricing-sources command", source, "bin/stint pricing-sources");
assertIncludes("integrations page documents pricing-models command", source, "bin/stint pricing-models");
assertIncludes("integrations page documents billing-prefs command", source, "bin/stint billing-prefs");
assertIncludes("integrations page documents billing-prefs upsert command", source, "bin/stint billing-prefs upsert billing-pref.json");
assertIncludes("integrations page documents billing-prefs delete command", source, "bin/stint billing-prefs delete codex");
assertIncludes("integrations page documents ai-costs command", source, "bin/stint ai-costs");
assertIncludes("integrations page documents ai-costs replace command", source, "bin/stint ai-costs replace ai-costs.json");
assertIncludes("integrations page documents leaderboards command", source, "bin/stint leaderboards");
assertIncludes("integrations page documents leaderboards create command", source, "bin/stint leaderboards create leaderboard.json");
assertIncludes("integrations page documents leaderboards update command", source, "bin/stint leaderboards update BOARD_ID leaderboard.json");
assertIncludes("integrations page documents leaderboards add-member command", source, "bin/stint leaderboards add-member BOARD_ID github-username");
assertIncludes("integrations page documents leaderboards remove-member command", source, "bin/stint leaderboards remove-member BOARD_ID USER_ID");
assertIncludes("integrations page documents leaderboards delete command", source, "bin/stint leaderboards delete BOARD_ID");
assertIncludes("integrations page documents share-tokens command", source, "bin/stint share-tokens");
assertIncludes("integrations page documents share-tokens create command", source, 'bin/stint share-tokens create "Public read"');
assertIncludes("integrations page documents share-tokens delete command", source, "bin/stint share-tokens delete SHARE_TOKEN_ID");
assertIncludes("integrations page documents events command", source, "bin/stint events");
assertIncludes("integrations page documents usage-events command", source, 'bin/stint usage-events --start "$(date +%F)" --end "$(date +%F)"');
assertIncludes("integrations page documents usage-events summary command", source, "bin/stint usage-events summary --range last_30_days --cost-mode calculate");
assertIncludes("integrations page documents usage-events blocks command", source, "bin/stint usage-events blocks --range last_7_days");
assertIncludes("integrations page documents data-dumps create command", source, "bin/stint data-dumps create heartbeats");
assertIncludes("integrations page documents daily data-dumps create command", source, "bin/stint data-dumps create daily");
assertIncludes("integrations page documents data-dumps command", source, "bin/stint data-dumps");
assertIncludes("integrations page documents data-dumps download command", source, "bin/stint data-dumps download DUMP_ID");
assertIncludes("integrations page documents custom-rules command", source, "bin/stint custom-rules");
assertIncludes("integrations page documents custom-rules replace command", source, "bin/stint custom-rules replace custom-rules.json");
assertIncludes("integrations page documents custom-rules delete command", source, "bin/stint custom-rules delete RULE_ID");
assertIncludes("integrations page documents custom-rules progress command", source, "bin/stint custom-rules progress");
assertIncludes("integrations page documents custom-rules abort command", source, "bin/stint custom-rules abort");
assertIncludes("integrations page documents WakaTime import command", source, "bin/stint import wakatime ~/Downloads/wakatime-dump.json");
assertIncludes("integrations page documents WakaTime import stdin command", source, "bin/stint import wakatime --stdin");
assertIncludes("integrations page documents file-experts subcommand", source, 'bin/stint file-experts "$PWD/main.go"');
assertIncludes("integrations page documents doctor command", source, "bin/stint doctor");
assertIncludes("integrations page documents collect command", source, "bin/stint collect");
assertIncludes("integrations page documents offline count subcommand", source, "bin/stint offline count");
assertIncludes("integrations page documents offline print subcommand", source, "bin/stint offline print");
assertIncludes("integrations page documents offline sync subcommand", source, "bin/stint offline sync");
assertIncludes("integrations page documents root file-experts mode", source, "--file-experts --entity");
assertIncludes("integrations page documents root offline count mode", source, "--offline-count");
assertIncludes("integrations page documents root offline print mode", source, "--print-offline-heartbeats");
assertIncludes("integrations page documents sync-ai-heartbeats alias", source, "--sync-ai-heartbeats");
assertIncludes("integrations page documents status bar enabled setting", source, "status_bar_enabled");
assertIncludes("integrations page documents status bar coding activity", source, "status_bar_coding_activity");
assertIncludes("integrations page documents hide_project_folder", source, "hide_project_folder");
assertIncludes("integrations page documents SSH host key alias support", source, "HostKeyAlias");
assertIncludes("integrations page documents strict host key checking support", source, "StrictHostKeyChecking");
assertIncludes("integrations page documents Antigravity AI sync support", source, "Antigravity");
assertIncludes("integrations page documents Codex apply-patch support", source, "Codex successful direct and shell apply-patch calls");
assertIncludes("integrations page documents Amp apply-patch AI sync support", source, "Amp apply-patch logs");
assertIncludes("integrations page documents Continue dev data AI sync support", source, "Continue dev data");
assertIncludes("integrations page documents Gemini project-root tool call support", source, "Gemini project-root tool calls");
assertIncludes("integrations page documents Kiro workspace action support", source, "Kiro workspace actions");
assertIncludes("integrations page documents Copilot CLI AI sync support", source, "Copilot CLI session-state");
assertIncludes("integrations page documents Copilot workspace AI sync support", source, "Copilot workspace storage");
assertIncludes("integrations page documents Qoder history AI sync support", source, "Qoder history");
assertIncludes("integrations page documents Qwen Code function-call support", source, "Qwen Code function-call tools");
assertIncludes("integrations page documents Windsurf Next SQLite support", source, "Windsurf Next");
assertIncludes("integrations page documents OpenCode SQLite support", source, "OpenCode SQLite");
assertIncludes("integrations page documents Cody SQLite chat history support", source, "Cody SQLite chat history");
assertIncludes("integrations page documents WakaTime AI sync state key", source, "internal.ai_logs_last_parsed_at");
assertIncludes("integrations page documents Codex prompt cleanup", source, "Codex prompt wrapper cleanup");
assertIncludes("integrations page documents AI subscription plan metadata", source, "subscription plan");
assertIncludes("integrations page documents AI read/write intent", source, "read/write intent");
assertIncludes("integrations page documents AI line change metadata", source, "ai_line_changes");
assertIncludes("integrations page documents prompt length metadata", source, "prompt length");
assertIncludes("integrations page marks integration catalog live", source, 'title: "Integration catalog", state: "live"');

function assertIncludes(name: string, sourceText: string, needle: string) {
  if (!sourceText.includes(needle)) {
    throw new Error(`${name}: expected source to include ${needle}`);
  }
}
