import { readFileSync } from "node:fs";
import assert from "node:assert/strict";

const source = readFileSync("app/(console)/integrations/page.tsx", "utf8");
const recipes = readFileSync("app/(console)/integrations/recipes.ts", "utf8");
const shell = readFileSync("components/shell.tsx", "utf8");
const apiSource = readFileSync("lib/api.ts", "utf8");
const packageJSON = readFileSync("package.json", "utf8");

assert.match(source, /Connect Stint/);
assert.match(source, /Choose where you code/);
assert.match(source, /activeToolCategory/);
assert.match(source, /setActiveToolCategory/);
assert.match(source, /Terminal/);
assert.match(source, /AI agents/);
assert.match(source, /Editors/);
assert.match(source, /listUserAgents/);
assert.match(source, /last_seen_at/);
assert.match(source, /Copy setup/);
assert.match(source, /Verify connection/);
assert.match(source, /setLatestKey/);
assert.match(source, /copyText/);
assert.match(source, /label="Copy"/);
assert.match(source, /selectedIntegration/);
assert.match(source, /setSelectedIntegration/);
assert.match(source, /aria-pressed/);
assert.match(source, /window\.history\.replaceState/);
assert.match(source, /integration-instructions/);
assert.doesNotMatch(source, /Connection health/);
assert.doesNotMatch(source, /Extended AI telemetry/);
assert.doesNotMatch(source, /StatusTile/);
assert.doesNotMatch(source, /Integration catalog/);
assert.match(recipes, /VS Code/);
assert.match(recipes, /JetBrains/);
assert.match(recipes, /Vim\/Neovim/);
assert.match(recipes, /Shell CLI/);
assert.match(recipes, /ai_model/);
assert.match(recipes, /llm_model/);
assert.match(recipes, /ai_provider/);
assert.match(source, /https:\/\/stint\.fyi\/api\/v1/);
assert.match(apiSource, /export type UserAgent/);
assert.match(apiSource, /ai_model/);
assert.match(apiSource, /ai_provider/);
assert.match(apiSource, /listUserAgents/);
assert.match(apiSource, /\/api\/v1\/users\/current\/user_agents/);
assert.match(shell, /\/integrations/);
assert.match(shell, /Integrations/);
assert.match(packageJSON, /scripts\/run-tests\.mjs/);
