export const clients = [
  {
    recipeId: "stint-cli-config",
    name: "Stint CLI",
    status: "live",
    description:
      "Use the native CLI for WakaTime-style heartbeats, status checks, projects, goals, file experts, and offline sync.",
    bullets: [
      "Drop-in root flags",
      "Git/Hg/SVN detection",
      "BoltDB offline queue",
    ],
  },
  {
    recipeId: "wakatime-cli-config",
    name: "WakaTime CLI",
    status: "supported",
    description:
      "Use the official CLI and existing editor plugins by changing the API URL and key.",
    bullets: [
      "Heartbeat ingestion",
      "Durations and summaries",
      "User-Agent editor parsing",
    ],
  },
  {
    recipeId: "codex-config",
    name: "Codex",
    status: "supported",
    description:
      "Codex heartbeats are parsed for editor, OS, agent, and version labels when available.",
    bullets: [
      "Agent attribution",
      "Token cost metrics",
      "Project and branch detection",
    ],
  },
  {
    recipeId: "vscode-config",
    name: "VS Code",
    status: "compatible",
    description:
      "Use the existing extension, then point the shared config file at Stint.",
    bullets: [
      "Extension marketplace",
      "Project/language charts",
      "Machine and OS breakdowns",
    ],
  },
  {
    recipeId: "jetbrains-config",
    name: "JetBrains",
    status: "compatible",
    description:
      "JetBrains IDEs work through the existing plugin and the same config file.",
    bullets: [
      "Basic and Bearer auth",
      "Project/language charts",
      "Machine and OS breakdowns",
    ],
  },
  {
    recipeId: "vim-config",
    name: "Vim/Neovim",
    status: "compatible",
    description:
      "Terminal editors can send standard activity check-ins to Stint.",
    bullets: [
      "Shared ~/.wakatime.cfg",
      "Project .wakatime overrides",
      "Branch and language inference",
    ],
  },
  {
    recipeId: "shell-cli-config",
    name: "Shell CLI",
    status: "compatible",
    description:
      "Use curl or any HTTP client to send WakaTime-shaped heartbeats directly.",
    bullets: ["Bearer auth", "JSON payloads", "Smoke-test friendly"],
  },
] as const;

export function integrationConfigs(apiURL: string, apiKey: string) {
  return [
    {
      id: "stint-cli-config",
      name: "Stint CLI",
      description:
        "Build the native client, initialize config, then send a compatibility heartbeat.",
      lines: [
        "make stint",
        `bin/stint config init --api-url ${apiURL} --api-key ${apiKey}`,
        "bin/stint api-keys",
        'bin/stint api-keys create "Editor key" --scope write_heartbeats --scope read_stats',
        "bin/stint api-keys delete API_KEY_ID",
        "bin/stint oauth-apps",
        'bin/stint oauth-apps create "Local OAuth app" --redirect-uri http://localhost:3000/callback --scope read_stats',
        "bin/stint oauth-apps delete OAUTH_APP_ID",
        "bin/stint oauth token --client-id OAUTH_CLIENT_ID --client-secret OAUTH_CLIENT_SECRET --code AUTH_CODE --redirect-uri http://localhost:3000/callback",
        "bin/stint oauth token --client-id OAUTH_CLIENT_ID --client-secret OAUTH_CLIENT_SECRET --refresh-token REFRESH_TOKEN",
        "bin/stint oauth revoke ACCESS_OR_REFRESH_TOKEN --client-id OAUTH_CLIENT_ID --client-secret OAUTH_CLIENT_SECRET",
        "bin/stint account",
        "bin/stint account update account.json",
        "bin/stint account delete --confirm",
        "bin/stint meta",
        "bin/stint api-docs",
        "bin/stint leaders",
        "bin/stint leaders --language Go --country US",
        "bin/stint editors",
        "bin/stint program-languages",
        "bin/stint users public-username",
        "bin/stint users public-username stats last_7_days",
        "bin/stint users public-username stats --range last_30_days",
        "bin/stint users public-username summaries",
        "bin/stint users public-username summaries --start 2026-06-01 --end 2026-06-30",
        "bin/stint share SHARE_TOKEN stats",
        "bin/stint share SHARE_TOKEN stats --range last_7_days",
        "bin/stint share SHARE_TOKEN summaries",
        "bin/stint share SHARE_TOKEN summaries --start 2026-06-01 --end 2026-06-30",
        "bin/stint health",
        "bin/stint health ingestion",
        "bin/stint dev seed-key --github-id 4001 --username local-dev",
        "bin/stint dev heartbeats-purge --retention-days 0",
        "bin/stint dev leaderboard-update --range last_7_days",
        "bin/stint dev goals-evaluate",
        'bin/stint heartbeat --entity "$PWD/main.go" --write --project stint',
        'bin/stint heartbeat --entity "$PWD/main.go" --category "ai coding" --ai-model gpt-5-codex --ai-provider openai --ai-agent codex --metadata \'{"source":"manual"}\'',
        'bin/stint heartbeats "$(date +%F)"',
        "bin/stint today",
        "bin/stint today --output json",
        "bin/stint today-goal 00000000-0000-4000-8000-000000000000",
        "bin/stint stats last_7_days",
        'bin/stint durations "$(date +%F)" --slice-by language',
        "bin/stint summaries 2026-06-01 2026-06-30",
        "bin/stint projects stint",
        "bin/stint projects stint commits --branch main",
        "bin/stint projects stint commits COMMIT_HASH",
        "bin/stint all-time",
        "bin/stint machine-names",
        "bin/stint user-agents",
        "bin/stint goals",
        "bin/stint goals create goal.json",
        "bin/stint goals update GOAL_ID goal.json",
        "bin/stint goals delete GOAL_ID",
        "bin/stint insights languages last_7_days",
        "bin/stint external-durations",
        "bin/stint external-durations create external-duration.json",
        "bin/stint external-durations bulk external-durations.json",
        "bin/stint external-durations delete 00000000-0000-4000-8000-000000000000",
        "bin/stint external-durations delete --ids id-1,id-2",
        "bin/stint custom-pricing",
        "bin/stint custom-pricing upsert custom-pricing.json",
        "bin/stint custom-pricing delete gpt-5-codex",
        "bin/stint pricing-sources",
        "bin/stint pricing-models",
        "bin/stint billing-prefs",
        "bin/stint billing-prefs upsert billing-pref.json",
        "bin/stint billing-prefs delete codex",
        "bin/stint ai-costs",
        "bin/stint ai-costs replace ai-costs.json",
        "bin/stint leaderboards",
        "bin/stint leaderboards create leaderboard.json",
        "bin/stint leaderboards update BOARD_ID leaderboard.json",
        "bin/stint leaderboards add-member BOARD_ID github-username",
        "bin/stint leaderboards remove-member BOARD_ID USER_ID",
        "bin/stint leaderboards delete BOARD_ID",
        "bin/stint share-tokens",
        'bin/stint share-tokens create "Public read"',
        "bin/stint share-tokens delete SHARE_TOKEN_ID",
        "bin/stint events",
        'bin/stint usage-events --start "$(date +%F)" --end "$(date +%F)"',
        "bin/stint usage-events summary --range last_30_days --cost-mode calculate",
        "bin/stint usage-events blocks --range last_7_days",
        "bin/stint data-dumps create heartbeats",
        "bin/stint data-dumps create daily",
        "bin/stint data-dumps",
        "bin/stint data-dumps download DUMP_ID",
        "bin/stint custom-rules",
        "bin/stint custom-rules replace custom-rules.json",
        "bin/stint custom-rules delete RULE_ID",
        "bin/stint custom-rules progress",
        "bin/stint custom-rules abort",
        "bin/stint import wakatime ~/Downloads/wakatime-dump.json",
        "gzip -dc ~/Downloads/wakatime-dump.json.gz | bin/stint import wakatime --stdin",
        'bin/stint file-experts "$PWD/main.go"',
        "bin/stint doctor",
        "bin/stint collect",
        'bin/stint --file-experts --entity "$PWD/main.go"',
        "bin/stint --offline-count",
        "bin/stint --print-offline-heartbeats 10",
        "bin/stint --sync-ai-activity",
        "bin/stint --sync-ai-heartbeats",
        "bin/stint offline count",
        "bin/stint offline print",
        "bin/stint offline sync",
      ],
    },
    {
      id: "wakatime-cli-config",
      name: "WakaTime CLI",
      description:
        "Install or keep the upstream CLI, then point its shared WakaTime config at Stint.",
      lines: [
        "pipx install wakatime",
        "mkdir -p ~/.wakatime",
        "cat > ~/.wakatime.cfg <<'EOF'",
        "[settings]",
        `api_url = ${apiURL}`,
        `api_key = ${apiKey}`,
        "heartbeat_rate_limit_seconds = 30",
        "offline = true",
        "EOF",
        'wakatime-cli --entity "$PWD/main.go" --write --plugin shell/1.0.0',
        "wakatime-cli --today",
        "wakatime-cli --offline-count",
        "wakatime-cli --sync-offline-activity",
      ],
    },
    {
      id: "codex-config",
      name: "Codex",
      description:
        "Use the native Stint CLI to sync local Codex sessions and emit model-aware AI activity.",
      lines: [
        "make stint",
        `bin/stint config init --api-url ${apiURL} --api-key ${apiKey}`,
        "bin/stint --sync-ai-activity --agent codex",
        "bin/stint --sync-ai-heartbeats --agent codex",
        'bin/stint heartbeat --entity "$PWD/main.go" --category "ai coding" --ai-agent codex --ai-provider openai --ai-model gpt-5-codex --write',
        "bin/stint today --output json",
        "bin/stint user-agents",
      ],
    },
    {
      id: "vscode-config",
      name: "VS Code",
      description: "Install the editor extension, then use this shared config.",
      lines: [
        "Install the WakaTime extension from the VS Code Marketplace.",
        "mkdir -p ~/.wakatime",
        "cat > ~/.wakatime.cfg <<'EOF'",
        "[settings]",
        `api_url = ${apiURL}`,
        `api_key = ${apiKey}`,
        "import_cfg = ~/.wakatime/private.cfg",
        "heartbeat_rate_limit_seconds = 30",
        "status_bar_enabled = true",
        "status_bar_show_categories = true",
        "status_bar_coding_activity = true",
        "EOF",
        "Reload VS Code, edit a file, then check Stint > Integrations for the latest user agent.",
      ],
    },
    {
      id: "jetbrains-config",
      name: "JetBrains",
      description:
        "Install the activity plugin from JetBrains Marketplace and reuse the same API URL.",
      lines: [
        "Install the WakaTime plugin from JetBrains Marketplace.",
        "mkdir -p ~/.wakatime",
        "cat > ~/.wakatime.cfg <<'EOF'",
        "[settings]",
        `api_url = ${apiURL}`,
        `api_key = ${apiKey}`,
        "heartbeat_rate_limit_seconds = 30",
        "hide_project_names = false",
        "EOF",
        "Restart the IDE, open a project, edit a file, then check Stint > Integrations for the JetBrains user agent.",
      ],
    },
    {
      id: "vim-config",
      name: "Vim/Neovim",
      description: "Keep a single config file for terminal editor plugins.",
      lines: [
        "Install vim-wakatime for Vim or Neovim.",
        "mkdir -p ~/.wakatime",
        "cat > ~/.wakatime.cfg <<'EOF'",
        "[settings]",
        `api_url = ${apiURL}`,
        `api_key = ${apiKey}`,
        "heartbeat_rate_limit_seconds = 30",
        "debug = false",
        "EOF",
        "Open Vim or Neovim, edit a tracked file, then run :WakaTimeApiKey if the plugin asks for a key.",
      ],
    },
    {
      id: "shell-cli-config",
      name: "Shell CLI",
      description: "Send a compatibility heartbeat directly for smoke testing.",
      lines: [
        `curl -X POST ${apiURL}/users/current/heartbeats \\`,
        `  -H "Authorization: Bearer ${apiKey}" \\`,
        '  -H "Content-Type: application/json" \\',
        '  -d \'{"entity":"~/src/stint/main.go","type":"file","time":1781887600,"project":"stint","language":"Go"}\'',
      ],
    },
  ] as const;
}

export const compatibilityNote =
  'For multi-endpoint configs, use{" "} [api_urls] and add{" "} .* = {apiURL}|waka_your_stint_key . The native CLI also reads{" "} [DEFAULT] top-level values, keeps runtime files directly under{" "} $WAKATIME_HOME/, validates and normalizes api_url, treats timeout = 0 as no HTTP timeout, treats non-integer{" "} heartbeat_rate_limit_seconds {" "} config as the WakaTime default, treats negative{" "} heartbeat_rate_limit_seconds {" "} as disabled, projectmap{" "} with capture placeholders,{" "} .wakatime-project{" "} {project} interpolation from Git remotes, Git submodule maps,{" "} project_api_key,{" "} api_key_vault_cmd, WakaTime legacy aliases like apikey,{" "} --api-key, and{" "} settings.ignore, case-insensitive scalar setting keys, quoted scalar values, ordered first-match project and API-key maps, all-match ordered api_urls fanout, and regex config, comma-separated include/exclude flags, newline-separated regex lists with commas preserved inside patterns, Perl-style lookahead regex fallback, HTTP/HTTPS/SOCKS/NTLM proxy settings, SSL options, machine/timezone request headers, dependency detection with WakaTime order and caps using the resolved or explicit language, WakaTime language aliases like{" "} CSharp,{" "} CPP,{" "} ObjectiveC, and{" "} Visual Basic .NET, and including side-effect and multi-line JavaScript/TypeScript imports, Scala grouped imports, multiline HTML script sources, Rust extern crate{" "} declarations, and Gruntfile{" "} as grunt, WakaTime-style 5 MiB automatic local file-stat reads for language, dependency, and line metadata with unsaved file entities skipping automatic line and dependency detection, Vim modelines for{" "} --guess-language, C-family, Objective-C, Matlab, Delphi, and F#/Forth language disambiguation, WakaTime top-language aliases such as{" "} crontab,{" "} .ruby-version,{" "} .Rprofile,{" "} .sublime-settings,{" "} .vue,{" "} .svh,{" "} .xaml,{" "} .xpl,{" "} .inc,{" "} .i,{" "} .j,{" "} .mo,{" "} .re,{" "} .swg, and{" "} .vm, dependency hiding,{" "} hide_project_names{" "} .wakatime-project aliases,{" "} hide_project_folder{" "} filename fallback, automatic SSH/SFTP remote stats with credential stripping and WakaTime-style remote filter skipping,{" "} --local-file overrides, and SSH config options such as{" "} HostName,{" "} User,{" "} Port,{" "} IdentityFile,{" "} UserKnownHostsFile,{" "} HostKeyAlias, and{" "} StrictHostKeyChecking.';
